name: housing_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.7
  - scikit-learn
  - pandas
  - numpy
  - pip
  - pip:
      - joblib
      - mlflow==2.19.0
      - dagshub
