name: CI Model Retraining & Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  retrain-and-deploy:
    runs-on: ubuntu-latest

    env:
      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
      MLFLOW_TRACKING_USERNAME: tianiayu
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.7

    - name: Check Python & Pip
      run: |
        python --version
        pip --version

    - name: Install Dependencies
      run: |
        pip install -r MLProject/requirements.txt || true
        pip install dagshub mlflow[extras] docker joblib

    - name: Train Model & Log Artifacts
      working-directory: MLProject
      run: python modelling.py

    - name: Prepare Docker Context
      run: |
        mkdir docker_context
        cp MLProject/model/*.joblib docker_context/
        cp Dockerfile docker_context/

    - name: Build Docker Image
      run: docker build -t houseprice-model docker_context

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "ciciayu" --password-stdin

    - name: Tag and Push Docker Image
      run: |
        docker tag houseprice-model:latest ciciayu/houseprice-model:latest
        docker push ciciayu/houseprice-model:latest

    - name: Upload Trained Model to GitHub Artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: MLProject/model

    - name: CI Completed
      run: echo " CI Workflow selesai dan image berhasil di-push ke Docker Hub!"
