name: CI Model Retraining

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  retrain:
    runs-on: ubuntu-latest

    env:
      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: housing_env
          environment-file: MLProject/conda.yaml
          auto-activate-base: false
          use-mamba: true

      - name: Install MLflow (pastikan tersedia di runner)
        shell: bash -l {0}
        run: |
          pip install mlflow

      - name: Run modelling.py directly
        shell: bash -l {0}
        run: |
           cd MLProject
           python modelling.py

      - name: Upload Trained Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: MLProject/model.joblib
