name: CI Model Retraining & Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  retrain-and-deploy:
    runs-on: ubuntu-latest

    env:
      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
      MLFLOW_TRACKING_USERNAME: tianiayu
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.7

    - name: Check Python & Env
      run: |
        python --version
        pip --version

    - name: Install Dependencies
      run: |
        pip install -r MLProject/requirements.txt || true
        pip install dagshub mlflow[extras] docker joblib

    - name: Run MLflow Project (modelling.py)
      working-directory: MLProject
      run: python modelling.py

    # Skipping mlflow models build-docker – not supported

    - name: Build Docker Image with Joblib Model
      run: |
        mkdir docker_context
        cp MLProject/model/* docker_context/
        cp Dockerfile docker_context/

        docker build -t houseprice-model docker_context

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag and Push Docker Image
      run: |
        docker tag houseprice-model:latest ${{ secrets.DOCKER_USERNAME }}/houseprice-model:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/houseprice-model:latest

    - name: Upload Trained Model to GitHub Artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: MLProject/model

    - name: Complete Job
      run: echo "CI Workflow Selesai dengan Sukses!"
