name: CI Model Retraining & Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  retrain-and-deploy:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: "https://dagshub.com/tianiayu/Membangun_model.mlflow"
      MLFLOW_TRACKING_USERNAME: "tianiayu"
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.7"

    - name: Install Dependencies
      run: |
        pip install -r MLProject/requirements.txt
        pip install dagshub mlflow jq docker

    - name: Run MLflow Project
      working-directory: MLProject
      run: python modelling.py

    - name: Get Best MLflow Run ID
      id: get_run_id
      run: |
        # Install jq if not already installed
        sudo apt-get install -y jq
        
        # Get the run with lowest MAE
        RUN_JSON=$(mlflow search-runs --experiment-name HousePricePrediction \
                  --order-by "metrics.mae ASC" \
                  --max-results 1 \
                  --format json)
        
        RUN_ID=$(echo "$RUN_JSON" | jq -r '.runs[0].info.run_id')
        echo "Best Run ID: $RUN_ID"
        echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

    - name: Verify Model URI
      run: |
        MODEL_URI="runs:/${{ steps.get_run_id.outputs.run_id }}/model"
        echo "Verifying model at: $MODEL_URI"
        mlflow models get-model-info -m "$MODEL_URI"

    - name: Build Docker Image
      run: |
        MODEL_URI="runs:/${{ steps.get_run_id.outputs.run_id }}/model"
        echo "Building Docker image for: $MODEL_URI"
        mlflow models build-docker -m "$MODEL_URI" -n "ciciayu/houseprice-model"

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker Image
      run: |
        docker push ciciayu/houseprice-model:latest

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trained-models
        path: MLProject/model
