name: CI Model Retraining & Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  retrain-and-deploy:
    runs-on: ubuntu-latest

    env:
      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
      MLFLOW_TRACKING_USERNAME: tianiayu
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python 3.12.7
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.7

    - name: Check Python & Env
      run: |
        python --version
        pip --version

    - name: Install Dependencies
      run: |
        pip install -r MLProject/requirements.txt
        pip install dagshub mlflow

    - name: Run MLflow Project
      working-directory: MLProject
      run: python modelling.py

    - name: Get Latest MLflow Run ID
      id: get_run_id
      run: |
        RUN_ID=$(mlflow search-runs -n HousePricePrediction --max-results 1 -o start_time DESC --columns run_id | tail -1)
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
        echo "Latest Run ID: $RUN_ID"

    - name: Install MLflow Extras for Build-Docker
      run: |
        pip install mlflow[extras]
        pip install docker

    - name: Build Docker Image from MLflow
      run: |
        mlflow models build-docker -m "runs:/${{ env.RUN_ID }}/model" -n houseprice-model

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker Image to Docker Hub
      run: |
        docker tag houseprice-model:latest ${{ secrets.DOCKER_USERNAME }}/houseprice-model:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/houseprice-model:latest

    - name: Upload Trained Model to GitHub Artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: MLProject/model
